defaults:
  - scope:
	  path: "Assets/Images"
	values:
	  image: true
title: SurfsUpðŸŒŠSDK
logo: /Assets/Images/sdk_logo.png
description: Map making documentation for SurfsUp
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
